export const GET_STUDENTS_PENDING = 'GET_STUDENTS_PENDING';
export const GET_STUDENTS_SUCCESS = 'GET_STUDENTS_SUCCESS';
export const GET_STUDENTS_FAILED = 'GET_STUDENTS_FAILED';

export const ADD_STUDENT_PENDING = 'ADD_STUDENT_PENDING';
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS';
export const ADD_STUDENT_FAILED = 'ADD_STUDENT_FAILED';

export const EDIT_STUDENT_PENDING = 'EDIT_STUDENT_PENDING';
export const EDIT_STUDENT_SUCCESS = 'EDIT_STUDENT_SUCCESS';
export const EDIT_STUDENT_FAILED = 'EDIT_STUDENT_FAILED';

export const DELETE_STUDENT_PENDING = 'DELETE_STUDENT_PENDING';
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
export const DELETE_STUDENT_FAILED = 'DELETE_STUDENT_FAILED';

export const CHANGE_ITEMS_COUNT = 'CHANGE_ITEMS_COUNT';